"""
BailBridge — PDF Document Generator

Uses ReportLab to produce styled bail-related documents (bail summaries,
defendant intake forms, agent referral sheets) as in-memory bytes ready
for upload or HTTP response streaming.
"""

import io
import datetime
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# ─────────────────────────────────────────────────────────────────────────────
# Style constants
# ─────────────────────────────────────────────────────────────────────────────

BRAND_BLUE = colors.HexColor("#1A3C5E")
BRAND_GOLD = colors.HexColor("#C9A84C")
LIGHT_GRAY = colors.HexColor("#F4F4F4")
MID_GRAY = colors.HexColor("#CCCCCC")


def _build_styles() -> dict:
    """Return a dict of named ParagraphStyles for the document."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "BailTitle",
            parent=base["Title"],
            fontSize=22,
            textColor=BRAND_BLUE,
            spaceAfter=4,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        ),
        "subtitle": ParagraphStyle(
            "BailSubtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=BRAND_GOLD,
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName="Helvetica-Oblique",
        ),
        "section": ParagraphStyle(
            "BailSection",
            parent=base["Normal"],
            fontSize=11,
            textColor=BRAND_BLUE,
            spaceBefore=10,
            spaceAfter=4,
            fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "BailBody",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.black,
            spaceAfter=4,
            fontName="Helvetica",
            leading=14,
        ),
        "footer": ParagraphStyle(
            "BailFooter",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER,
            fontName="Helvetica-Oblique",
        ),
        "label": ParagraphStyle(
            "BailLabel",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.gray,
            fontName="Helvetica-Oblique",
        ),
        "value": ParagraphStyle(
            "BailValue",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.black,
            fontName="Helvetica",
        ),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _header(styles: dict, title: str, subtitle: str) -> list:
    """Return a list of flowables that form the document header."""
    return [
        Paragraph("BailBridge", styles["title"]),
        Paragraph(subtitle, styles["subtitle"]),
        HRFlowable(width="100%", thickness=2, color=BRAND_GOLD, spaceAfter=12),
        Paragraph(title, styles["section"]),
        Spacer(1, 0.1 * inch),
    ]


def _key_value_table(data: dict, styles: dict) -> Table:
    """
    Render a two-column label/value table from a flat dict.
    Keys become labels; values become formatted cell content.
    """
    rows = [
        [
            Paragraph(str(k), styles["label"]),
            Paragraph(str(v) if v is not None else "—", styles["value"]),
        ]
        for k, v in data.items()
    ]
    table = Table(rows, colWidths=[2.2 * inch, 4.3 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_GRAY]),
                ("GRID", (0, 0), (-1, -1), 0.25, MID_GRAY),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return table


def _footer(styles: dict) -> list:
    """Return footer flowables."""
    generated_at = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return [
        Spacer(1, 0.3 * inch),
        HRFlowable(width="100%", thickness=0.5, color=MID_GRAY),
        Spacer(1, 0.05 * inch),
        Paragraph(
            f"Generated by BailBridge · {generated_at} · Confidential Legal Document",
            styles["footer"],
        ),
    ]


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_bail_summary(
    case_id: str,
    defendant_name: str,
    charge: str,
    bail_amount: float,
    court_date: str,
    court_location: str,
    agent_name: Optional[str] = None,
    agent_phone: Optional[str] = None,
    notes: Optional[str] = None,
) -> bytes:
    """
    Generate a Bail Case Summary PDF.

    Args:
        case_id:        Unique case identifier.
        defendant_name: Full name of the defendant.
        charge:         Primary charge or offence description.
        bail_amount:    Bail amount in USD.
        court_date:     Scheduled court date string (e.g. '2025-08-15').
        court_location: Name/address of the court.
        agent_name:     Optional bail agent full name.
        agent_phone:    Optional bail agent contact number.
        notes:          Optional freeform notes to include at the bottom.

    Returns:
        PDF document as raw bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=inch,
        rightMargin=inch,
    )
    styles = _build_styles()
    story = []

    # Header
    story += _header(styles, "Bail Case Summary", "Confidential — Legal Document")

    # Defendant details
    story.append(Paragraph("Defendant Information", styles["section"]))
    story.append(
        _key_value_table(
            {
                "Case ID": case_id,
                "Defendant Name": defendant_name,
                "Primary Charge": charge,
                "Bail Amount": f"${bail_amount:,.2f}",
                "Court Date": court_date,
                "Court Location": court_location,
            },
            styles,
        )
    )

    # Agent details (optional)
    if agent_name or agent_phone:
        story.append(Spacer(1, 0.15 * inch))
        story.append(Paragraph("Assigned Bail Agent", styles["section"]))
        story.append(
            _key_value_table(
                {
                    "Agent Name": agent_name or "—",
                    "Contact Number": agent_phone or "—",
                },
                styles,
            )
        )

    # Notes (optional)
    if notes:
        story.append(Spacer(1, 0.15 * inch))
        story.append(Paragraph("Additional Notes", styles["section"]))
        story.append(Paragraph(notes, styles["body"]))

    story += _footer(styles)

    doc.build(story)
    return buffer.getvalue()


def generate_intake_form(
    case_id: str,
    defendant_name: str,
    dob: str,
    address: str,
    phone: str,
    emergency_contact: str,
    employment_status: Optional[str] = None,
    prior_convictions: Optional[str] = None,
) -> bytes:
    """
    Generate a Defendant Intake Form PDF.

    Args:
        case_id:            Unique case identifier.
        defendant_name:     Full name of the defendant.
        dob:                Date of birth string (e.g. '1990-03-22').
        address:            Current residential address.
        phone:              Contact phone number.
        emergency_contact:  Name and number of emergency contact.
        employment_status:  Optional employment status description.
        prior_convictions:  Optional prior conviction summary.

    Returns:
        PDF document as raw bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=inch,
        rightMargin=inch,
    )
    styles = _build_styles()
    story = []

    story += _header(styles, "Defendant Intake Form", "Confidential — Legal Document")

    story.append(Paragraph("Personal Information", styles["section"]))
    story.append(
        _key_value_table(
            {
                "Case ID": case_id,
                "Full Name": defendant_name,
                "Date of Birth": dob,
                "Address": address,
                "Phone Number": phone,
                "Emergency Contact": emergency_contact,
                "Employment Status": employment_status or "Not provided",
                "Prior Convictions": prior_convictions or "None disclosed",
            },
            styles,
        )
    )

    # Signature block
    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph("Declaration", styles["section"]))
    story.append(
        Paragraph(
            "I hereby certify that the information provided above is true and accurate "
            "to the best of my knowledge. I understand that providing false information "
            "may result in legal consequences.",
            styles["body"],
        )
    )
    story.append(Spacer(1, 0.5 * inch))

    sig_table = Table(
        [
            ["_" * 40, "", "_" * 25],
            ["Defendant Signature", "", "Date"],
        ],
        colWidths=[3.5 * inch, 0.5 * inch, 2.5 * inch],
    )
    sig_table.setStyle(
        TableStyle([("FONTSIZE", (0, 1), (-1, 1), 8), ("TEXTCOLOR", (0, 1), (-1, 1), colors.gray)])
    )
    story.append(sig_table)

    story += _footer(styles)
    doc.build(story)
    return buffer.getvalue()
